// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://passtnsttaxaaauovxnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhc3N0bnN0dGF4YWFhdW92eG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODk3OTQsImV4cCI6MjA2NzY2NTc5NH0.fBJs5BUPXSXRTN3D3kq0zcaiMDCgESnzBpNOpBfK6Bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});